version: '3.9'

services:
  pods:
    build: .
    deploy:
      replicas: 4
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/tech-ks-quartz?currentSchema=public"
    restart: always
  db:
    container_name: "db"
    image: postgres:12.3
    environment:
      - POSTGRES_DB=tech-ks-quartz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5